# 1. Pod를 DaemonSet으로 변환
# 2. 파드 템플릿은 spec의 필수 필드
# 3. 템플릿은 파드와 apiVersion 또는 kind 제외하고 같은 구조
# 4. 파드 셀렉터는 템플릿의 레이블과 매치되야 함
# 5. 셀렉터는 matchLabels와 matchExpressions로 구성
# 6. nodeSelector의 경우 일치하는 노드에 파드 생성
#  2024-05-10 2018108254 김태경

apiVersion: apps/v1 # v1 -> apps/v1
kind: DaemonSet # 1. 변환
metadata:
  name: numbers-api
  labels:
    kiamol: ch06-lab
spec:
  selector: # 4. 셀렉터
    matchLabels:
      app: numbers-api
  template: # 2. 템플릿은 파드와 같은 구조
    metadata:
      labels:
        app: numbers-api
    spec:
      containers:
        - name: api
          image: kiamol/ch03-numbers-api
      nodeSelector: #6.노드셀렉터
        rng: hw
